version: "3.6"
networks:
  devops-net:
    driver: bridge
volumes:
  gitlab-config:
    name: gitlab-config
  gitlab-logs:
    name: gitlab-logs
  gitlab-data:
    name: gitlab-data
  mysql-data:
    name: mysql-data
  mysql-conf.d:
    name: mysql-conf.d
  jira-data:
    name: jira-data
  jira-logs:
    name: jira-logs
  confluence-data:
    name: confluence-data
  confluence-logs:
    name: confluence-logs
services:
  gitlab:
    container_name: devops_gitlab
    image: gitlab/gitlab-ce:latest 
    restart: always
    hostname: 'gitlab'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
              external_url 'http://gitlab.devops'
              gitlab_rails['time_zone'] = 'Asia/Shanghai'
              gitlab_rails['gitlab_email_enabled'] = true
              gitlab_rails['gitlab_email_from'] = '926095480@qq.com'
              gitlab_rails['gitlab_email_display_name'] = 'devops'
              gitlab_rails['gitlab_email_reply_to'] = '926095480@qq.com'
              gitlab_rails['gitlab_email_subject_suffix'] = ''
              gitlab_rails['smtp_enable'] = true
              gitlab_rails['smtp_address'] = "smtp.qq.com"
              gitlab_rails['smtp_port'] = 465 
              gitlab_rails['smtp_user_name'] = "926095480@qq.com"
              gitlab_rails['smtp_password'] = "wrtjoqscuuvrbchj" 
              gitlab_rails['smtp_domain'] = "smtp.qq.com"
              gitlab_rails['smtp_authentication'] = "login"
              gitlab_rails['smtp_enable_starttls_auto'] = true
              gitlab_rails['smtp_tls'] = true
    networks:
      devops-net:
        aliases:
          - gitlab
    expose:
      - 80
    volumes:
      - gitlab-config:/etc/gitlab/
      - gitlab-data:/var/opt/gitlab/
      - gitlab-logs:/var/log/gitlab/
    logging:
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "50"
  mysql:
    image: mysql:5.7
    container_name: devops_mysql57
    restart: always
    networks:
      devops-net:
        aliases:
          - mysql
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=devOps12121212
      - TZ='Asia/Shanghai'
    command: ['mysqld', '--default-storage-engine=INNODB','--innodb_large_prefix=ON','--innodb_default_row_format=DYNAMIC','--character-set-server=utf8mb4', '--collation-server=utf8mb4_bin','--transaction-isolation=READ-COMMITTED', '--innodb_log_file_size=1G', '--max_allowed_packet=256M','--innodb_file_format=Barracuda']
    volumes:
      - mysql-data:/var/lib/mysql/
      - mysql-conf.d:/etc/mysql/conf.d/
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    logging:
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "50"
  jira:
    build: ./build/jira
    container_name: devops_jira
    environment:
      - TZ='Asia/Shanghai'
    restart: always
    networks:
        devops-net:
          aliases:
            - jira
    expose:
      - 8080
    volumes:
        - jira-data:/var/atlassian/jira/
        - jira-logs:/opt/atlassian/jira/logs/
    depends_on:
      - mysql
  confluence:
    build: ./build/confluence
    container_name: devops_confluence
    environment:
      - TZ='Asia/Shanghai'
    restart: always
    networks:
      devops-net:
        aliases:
          - confluence
    expose:
      - 8090
    volumes:
      - confluence-data:/var/atlassian/confluence/
      - confluence-logs:/opt/atlassian/confluence/logs/
    depends_on:
      - mysql
  
